#ifndef XIFTY_H
#define XIFTY_H

#pragma once

/* This file is generated by cbindgen. Do not edit it directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum XiftyStatusCode {
  XIFTY_STATUS_CODE_SUCCESS = 0,
  XIFTY_STATUS_CODE_INVALID_ARGUMENT = 1,
  XIFTY_STATUS_CODE_IO_ERROR = 2,
  XIFTY_STATUS_CODE_UNSUPPORTED_FORMAT = 3,
  XIFTY_STATUS_CODE_PARSE_ERROR = 4,
  XIFTY_STATUS_CODE_INTERNAL_ERROR = 5,
} XiftyStatusCode;

typedef enum XiftyViewMode {
  XIFTY_VIEW_MODE_FULL = 0,
  XIFTY_VIEW_MODE_RAW = 1,
  XIFTY_VIEW_MODE_INTERPRETED = 2,
  XIFTY_VIEW_MODE_NORMALIZED = 3,
  XIFTY_VIEW_MODE_REPORT = 4,
} XiftyViewMode;

typedef struct XiftyBuffer {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t capacity;
} XiftyBuffer;

typedef struct XiftyResult {
  enum XiftyStatusCode status;
  struct XiftyBuffer output;
  struct XiftyBuffer error_message;
} XiftyResult;

struct XiftyResult xifty_probe_json(const char *path);

struct XiftyResult xifty_extract_json(const char *path, enum XiftyViewMode view_mode);

void xifty_free_buffer(struct XiftyBuffer buffer);

const char *xifty_version(void);

#endif  /* XIFTY_H */

